Tasks 91-104
KamilWasilonek/ui-internship-lwo2 pull request #10
Opened 2019-05-13 15:32 UTC by KamilWasilonek

2019-05-14 10:12 UTC, tkachukivan requested changes
please make changes to 96, 99 and 100/101 optional :)

2019-05-14 10:12 UTC, tkachukivan commented on tasks/100_greatest-common-divisor/greatest-common-divisor.js
> +  arg = arg[0] > arg[1] ? arg.reverse() : arg;
Euclidan Algorithm will looks better here

2019-05-14 10:12 UTC, tkachukivan commented on tasks/101_least-common-multiple/least-common-multiple.js
> +  let firstArgMultiply = arg1;
there is a formula with using greatestCommonDivisor, with it solution can be better and probably faster

2019-05-14 10:12 UTC, tkachukivan commented on tasks/102_linked-list/linked-list.js
> +  this.amount += 1;
`this.amount++`

2019-05-14 10:12 UTC, tkachukivan commented on tasks/102_linked-list/linked-list.js
> +      if (current == this.head && current == this.tail) {
`===` instead of `==`

2019-05-14 10:12 UTC, tkachukivan commented on tasks/103_stack/stack.js
> +    this.size += 1;
in both cases you update size and isEmpty, maybe you can move this outside of your ifs to not repeat yourself

2019-05-14 10:12 UTC, tkachukivan commented on tasks/103_stack/stack.js
> +    this.size -= 1;
this.size--

2019-05-14 10:12 UTC, tkachukivan commented on tasks/91_inventory-update/inventory-update.js
> +        return a.localeCompare(b);
👍 

but one point one not in one line `(a, b) => a.localeCompare(b)`

2019-05-14 10:12 UTC, tkachukivan commented on tasks/93_make-a-person/make-a-person.js
> +    fullName = fullName.split(' ');
other way would be call setFullName function here, and don't keep fullName but keep first and second, it is easier to concatenate two strings that split every time one

2019-05-14 10:12 UTC, tkachukivan commented on tasks/95_pairwise/pairwise.js
> +        arr[index] = '';
what is a reason to reset current value? you will not return to this value anyway

2019-05-14 10:12 UTC, tkachukivan commented on tasks/96_how-many-differences-of-squares/how-many-differences-of-squares.js
> +  for (let i = 1; i <= howManyNumbers; i++) {
are you sure that you need loop here

2019-05-14 10:12 UTC, tkachukivan commented on tasks/99_fat-fingers/fat-fingers.js
> +  transformedStr = transformedStr.replace(/[aA]/g, '');
what about reduce method and do it without replace?

2019-05-15 12:59 UTC, tkachukivan requested changes

2019-05-15 12:59 UTC, tkachukivan commented on tasks/93_make-a-person/make-a-person.js
> -    this.fullName = this._firstName + ' ' + this._lastName;
with this changes when you set fullName, your first and last name remains as they was

2019-05-16 10:55 UTC, tsvetkovv requested changes

2019-05-16 10:55 UTC, Tsvetkovv commented on tasks/103_stack/stack.js
> +  }
repeated code in both of branches. Can be simplified

2019-05-16 10:55 UTC, Tsvetkovv commented on tasks/103_stack/stack.js
> +  } else {
`else` is not required here - `return` is in the first branch of condition

2019-05-16 10:55 UTC, Tsvetkovv commented on tasks/93_make-a-person/make-a-person.js
> +    this._firstName = dividedFullName[0];
you have setter for it

2019-05-16 10:55 UTC, Tsvetkovv commented on tasks/93_make-a-person/make-a-person.js
> +}
You have dependencies: 

1. first name depends on full name and vice versa. If you set first name, you should update fullName as well and vice versa
2. last name depends on full name and vice versa. If you set last name, you should update fullName as well and vice versa

unfortunately, tests are not covered this case. But it's real production case. It is too hard to keep up to date both source of truth, so please try to **have only one source of truth**. For example, only first + last name in this class

**steps to reproduce**: set  another full name, get first name.
**expected result**: first name should be updated
The same for second name.

2019-05-16 10:55 UTC, Tsvetkovv commented on tasks/93_make-a-person/make-a-person.js
> +}
And partial test does not work
![image](https://user-images.githubusercontent.com/11594423/57847106-f1348080-77d5-11e9-985d-0862771a7c18.png)

2019-05-16 10:55 UTC, Tsvetkovv commented on tasks/95_pairwise/pairwise.js
> +        arrToSearch[i] = '';
here `arrToSearch[i] === arr[i]`
and `arrToSearch === arr`. It's the same object in memory

The method what calls `pairwise` does not expect that input array would be changed

2019-05-16 10:55 UTC, Tsvetkovv commented on tasks/95_pairwise/pairwise.js
> +  let arrToSearch = arr;
btw, what this variable for? It has never read

2019-05-16 10:55 UTC, Tsvetkovv commented on tasks/95_pairwise/pairwise.js
> +export function pairwise(arr, num) {
num - sum?

2019-05-16 10:55 UTC, Tsvetkovv commented on tasks/95_pairwise/pairwise.js
> +export function pairwise(arr, num) {
or `expectedSum`

2019-05-17 08:28 UTC, tkachukivan approved these changes

2019-06-07 07:56 UTC, tsvetkovv approved these changes
Well done!

2019-06-07 07:58 UTC, merged