Task 1
KamilWasilonek/ui-internship-lwo2 pull request #12
Opened 2019-05-24 12:01 UTC by KamilWasilonek

https://kamilwasilonek.github.io/ui-internship-lwo2/html/Task_1

2019-05-28 08:30 UTC, tsvetkovv requested changes

2019-05-28 08:30 UTC, Tsvetkovv commented on html/Task_1/index.html
> +                            N<sup><u>o</u></sup>
wow :)
№

2019-05-28 08:30 UTC, Tsvetkovv commented on html/Task_1/index.html
> +                    <table>
Why do you use table here? 🤔

2019-05-28 08:30 UTC, Tsvetkovv commented on html/Task_1/index.html
> +          <font size="8">Markup of “Basic HTML” task</font>
Better to use `<h*>` elements

2019-05-28 08:30 UTC, Tsvetkovv commented on html/Task_1/index.html
> +                <th><font size="5">Main Content</font></th>
the same, `h*` element

2019-05-28 08:30 UTC, Tsvetkovv commented on html/Task_1/index.html
> +            <table cellpadding="5px">
why is table here?

2019-05-28 13:57 UTC, tkachukivan approved these changes

2019-05-29 11:10 UTC, tsvetkovv approved these changes
Well done

2019-05-30 08:10 UTC, merged