Html task 2
KamilWasilonek/ui-internship-lwo2 pull request #21
Opened 2019-05-28 09:32 UTC by KamilWasilonek

https://kamilwasilonek.github.io/ui-internship-lwo2/html/Task_2/

2019-05-28 14:38 UTC, tkachukivan approved these changes
Generally it would be more logic if by default you would have checkboxes selected and when user unselect it don't show some info

2019-05-28 16:39 UTC, tsvetkovv requested changes
It's not appropriate for production web-site
![Kapture 2019-05-28 at 18 37 27](https://user-images.githubusercontent.com/11594423/58495462-d4a22c00-8177-11e9-8622-77b4668586d8.gif)

2019-05-29 08:30 UTC, tsvetkovv approved these changes

2019-05-29 08:30 UTC, Tsvetkovv commented on html/Task_2/style.css
> +  display: none;
the same rule for 3 selectors. Could you union this?

2019-05-29 08:30 UTC, Tsvetkovv commented on html/Task_2/style.css
> +  display: none;
the same for opacity

2019-05-29 08:52 UTC, merged