Ellipsis
KamilWasilonek/ui-internship-lwo2 pull request #26
Opened 2019-06-07 10:54 UTC by KamilWasilonek

https://kamilwasilonek.github.io/ui-internship-lwo2/html/Ellipsis/

2019-06-11 12:12 UTC, tsvetkovv requested changes

2019-06-11 12:12 UTC, tsvetkovv commented on html/Ellipsis/index.html
> +      <p>
`p` cannot be inside `button`

2019-06-11 12:12 UTC, tsvetkovv commented on html/Ellipsis/index.html
> +    <button type="button" class="card card-1">
I think it's not button, just `a` element. They don't look as button

2019-06-11 12:12 UTC, Tsvetkovv commented on html/Ellipsis/index.html
> +          <br>
please avoid using br except poems and addresses
https://stackoverflow.com/a/1726103
use `<p>` for splitting by paragraphs

2019-06-11 12:12 UTC, Tsvetkovv commented on html/Ellipsis/index.html
> +          <img src="./assets/development/shape-3.png" alt="Development">
I think it's just decorative icon, `alt` attribute should be empty
https://support.siteimprove.com/hc/en-gb/articles/115000013031-Accessibility-Image-Alt-text-best-practices

2019-06-11 12:12 UTC, Tsvetkovv commented on html/Ellipsis/style.css
> +  position: absolute;
For every section (about us, services, what to do etc) you reinvent title styling — not scalable solution. Please think how to make it universal

2019-06-11 12:12 UTC, Tsvetkovv commented on html/Ellipsis/index.html
> +          <br>
and please take care of every entry of `br`

2019-06-25 11:02 UTC, tkachukivan commented on html/Ellipsis/index.html
> +      <header class="about-us__title section-title">
it should be h* tag

2019-06-25 11:02 UTC, tkachukivan commented on html/Ellipsis/index.html
> +        <p class="description__text">
there is bigger distance between lines in mockup for all text blocks

2019-06-25 11:02 UTC, tkachukivan commented on html/Ellipsis/index.html
> +      <div class="services__line"></div>
maybe possible to do as for about section without additional element

2019-06-25 11:02 UTC, tkachukivan commented on html/Ellipsis/style.css
> +    url("./assets/banner/layer-8@2x-min.png") no-repeat right center;
it is good to have some space to not being confused with properties

2019-06-26 07:59 UTC, tkachukivan commented on html/Ellipsis/index.html
> +    <section class="what-we-do">
try not to name classes by content, as content can change

2019-06-28 18:04 UTC, tsvetkovv approved these changes

2019-07-01 09:11 UTC, tkachukivan approved these changes

2019-07-12 07:25 UTC, merged