Product
KamilWasilonek/ui-internship-lwo2 pull request #27
Opened 2019-06-10 14:10 UTC by KamilWasilonek

https://kamilwasilonek.github.io/ui-internship-lwo2/html/Product/

2019-06-11 10:12 UTC, tsvetkovv requested changes

2019-06-11 10:12 UTC, tsvetkovv commented on html/Product/index.html
> +        clear selection
https://www.w3schools.com/tags/att_button_type.asp
https://www.w3schools.com/tags/att_input_type_reset.asp

2019-06-11 10:12 UTC, tsvetkovv commented on html/Product/index.html
> +        <span class="navbar__separator"></span>
please try to implement separators as borders

2019-06-11 10:12 UTC, tsvetkovv commented on html/Product/index.html
> +      <div class="images__big-img"></div>
You can google some [image](https://placeimg.com) [placeholders](https://placeholder.com) and put it there. Just for funny development 😄

2019-06-11 10:12 UTC, tsvetkovv commented on html/Product/index.html
> +      <div class="images__big-img"></div>
and not just for fun. If you open the site on wide-screen with real images, you see that they are stretched.
![image](https://user-images.githubusercontent.com/11594423/59260687-57c58680-8c3c-11e9-8714-f52fc1ed6444.png)
p.s. is there no limitation for stretching on wide-screens?

2019-06-11 10:12 UTC, tsvetkovv commented on html/Product/index.html
> +        <p>|</p>
border?

2019-06-11 10:12 UTC, tsvetkovv commented on html/Product/index.html
> +          <label for="color">COLOR</label>
The value of the `for` attribute must be the ID of input

2019-06-11 10:12 UTC, Tsvetkovv commented on html/Product/style.css
> +  padding: 10px 0 10px 10px;
why zero? why 130%?

2019-06-25 10:32 UTC, tkachukivan approved these changes

2019-06-25 10:32 UTC, tkachukivan commented on html/Product/index.html
> +          <button class="bookmarks__button-1" type="submit">
button-1 and button-2 bad class names, this buttons have a lot in common, different only color/background why not make something as base styles and with modifiers when needed change background and color

2019-06-28 18:09 UTC, tsvetkovv approved these changes

2019-07-12 07:25 UTC, merged