Corporate
KamilWasilonek/ui-internship-lwo2 pull request #28
Opened 2019-06-17 08:39 UTC by KamilWasilonek

https://kamilwasilonek.github.io/ui-internship-lwo2/html/Corporate/

2019-06-19 06:59 UTC, mikhail-ev requested changes

2019-06-19 06:59 UTC, TargetTaiga commented on html/Corporate/index.html
> +      <button class="banner__try-now" type="button">Try now</button>
i would suggest do not name classes by content, try to use something like "action", "interaction", "button", etc

2019-06-19 06:59 UTC, TargetTaiga commented on html/Corporate/index.html
> +      <p class="unique-platform__description unique-platform__description--margin">
also avoid to use css property names in classes, I would suggest "spaced", "extra space". As in the case with content inside class name this approach would confuse if the type of CSS property was changed but the result has remained the same

2019-06-19 06:59 UTC, TargetTaiga commented on html/Corporate/style.css
> +  padding-bottom: 200px;
why's overrode?

2019-06-19 06:59 UTC, TargetTaiga commented on html/Corporate/style.css
> +  padding-bottom: 100px;
banner has same spacings may be it's connected, please check

2019-06-19 06:59 UTC, TargetTaiga commented on html/Corporate/style.css
> +  padding-bottom: 100px;
same spacing again

2019-06-19 06:59 UTC, TargetTaiga commented on html/Corporate/style.css
> +  padding-bottom: 100px;
and again

2019-06-19 06:59 UTC, TargetTaiga commented on html/Corporate/style.css
> +.contact-form__input::placeholder {
if this selectors should apply the same result write them in comma separated list like 
`.contact-form__input::-webkit-input-placeholder, 
.contact-form__input:-ms-input-placeholder
`

2019-06-19 06:59 UTC, TargetTaiga commented on html/Corporate/style.css
> +  padding-bottom: 100px;
here we go again

2019-06-26 08:30 UTC, tkachukivan requested changes
you have a lot pixel values maybe some of them is possible to change to % to make site more responsive with less media queries(just a suggestion not spend a lot time for this)

2019-06-26 08:30 UTC, tkachukivan commented on html/Corporate/index.html
> +          <img class="feature__icon" src="./assets/image-icon/picture@2x.png" alt="">
empty alt here and below for features images

2019-06-26 08:30 UTC, tkachukivan commented on html/Corporate/index.html
> +  <!-- Awsome feature -->
awEsome :D

2019-06-26 08:30 UTC, tkachukivan commented on html/Corporate/index.html
> +      <button class="contact-form__submit submit" type="submit">Try now</button>
submit is default type

2019-06-26 08:30 UTC, tkachukivan commented on html/Corporate/index.html
> +    <div class="footer__container">
there is address tag and a tag with tel in href, it is very useful

2019-06-26 08:30 UTC, tkachukivan commented on html/Corporate/index.html
> +      <a href="#">Help Center</a>
it is probably list of links, same below

2019-06-26 08:30 UTC, tkachukivan commented on html/Corporate/style.css
> +@import url("https://fonts.googleapis.com/css?family=Exo:300,400,700&display=swap");
general suggestion you don't have to push compiled style(and specially sourcemaps) to this branch, they need probably only for gh-pages, try keep in github only your source code, not compiled code(if there is no reason for it)

2019-06-26 08:30 UTC, tkachukivan commented on html/Corporate/style.scss
> +@import url("https://fonts.googleapis.com/css?family=Exo:300,400,700&display=swap");
using scss you can split you files(by blocks, functionality, components anything what have sense for certain mockup) (here you have comments by section it is can be good separation to files) and import to one, it is much easier to work with a few small files than with one big file

2019-06-26 08:30 UTC, tkachukivan commented on html/Corporate/style.scss
> +$color-secondary: #f04c4c;
separate file for variables

2019-06-26 08:30 UTC, tkachukivan commented on html/Corporate/style.scss
> +@mixin section-type() {
separate file for mixins

2019-06-26 08:30 UTC, tkachukivan commented on html/Corporate/style.scss
> +@mixin default-padding ($left: 10%, $right: 10%, $top: 100px, $bottom: 100px) {
in case like with default values you can use shortcut padding and don't use mixin at all

2019-06-26 08:30 UTC, tkachukivan commented on html/Corporate/style.scss
> +  @include vertical-padding(200px, 200px);
whoudn't it easier just use padding css property

2019-06-26 08:30 UTC, tkachukivan commented on html/Corporate/style.scss
> +@media screen and (min-width: 1024px) {
it is posible to write media queries right under class properties, same applies below
```
.banner {
  // your css
  @media screen and (min-width: 1024px) {
    // your media changes
  }
}
```

2019-07-01 08:28 UTC, tkachukivan approved these changes

2019-07-01 08:28 UTC, tkachukivan commented on html/Corporate/styles/style.scss
> +* {
generally better have imports and then styles if you have them in same file

2019-07-01 08:28 UTC, tkachukivan commented on .gitignore
> +*.css
just be aware of case when you can ignore needed .css files(you may not face it if all your files is scss)

2019-07-12 07:26 UTC, merged