Axit
KamilWasilonek/ui-internship-lwo2 pull request #29
Opened 2019-06-24 15:12 UTC by KamilWasilonek

https://kamilwasilonek.github.io/ui-internship-lwo2/html/Axit/

2019-06-28 08:27 UTC, tkachukivan requested changes
It would be great to change a bit inputs on focus, for example change border color

2019-06-28 08:27 UTC, tkachukivan commented on html/Axit/index.html
> +    <div class="tabs__tab-container">
also sometimes it is possible to do as list of buttons/links

2019-06-28 08:27 UTC, tkachukivan commented on html/Axit/index.html
> +      <span class="separator sub-list__separator "></span>
maybe before/after as it is decoration element

2019-06-28 08:27 UTC, tkachukivan commented on html/Axit/index.html
> +          <div class="sub-list-service__text">
details would be more describable than text

2019-06-28 08:27 UTC, tkachukivan commented on html/Axit/index.html
> +  <section class="awsome-things">
awEsome

2019-06-28 08:27 UTC, tkachukivan commented on html/Axit/styles/style.scss
> +    &__menu {
maybe there is a reason to write just `navbar__menu`

2019-06-28 08:27 UTC, tkachukivan commented on html/Axit/styles/style.scss
> +@import url('https://fonts.googleapis.com/css?family=Open+Sans:300,400,700&display=swap');
it would be a bit easier to work with this if separate to a few files

2019-06-28 08:27 UTC, tkachukivan commented on html/Axit/index.html
> +    <header class="navbar banner__navbar">
this header is not related to section and can be by itself

2019-06-28 08:27 UTC, tkachukivan commented on html/Axit/index.html
> +        <button class="price pricing__price">
I'm not sure if it button, as probably it is not and it is just a block, generally your button will have no other tags, maybe some spans

2019-06-28 08:27 UTC, tkachukivan commented on html/Axit/index.html
> +          <div class="customer__names">
not sure if customer position is part of his name, maybe some more general class name would be better here

2019-06-28 08:27 UTC, tkachukivan commented on html/Axit/index.html
> +        <input class="form__input contact__message" type="text" placeholder="Message">
it is textarea not input

2019-06-28 18:46 UTC, tsvetkovv approved these changes

2019-07-01 09:09 UTC, tkachukivan approved these changes

2019-07-01 09:09 UTC, tkachukivan commented on .gitignore
> +*.css
i hope you will not have conflict with other branch

2019-07-10 10:45 UTC, merged