Added tasks 21-30
KamilWasilonek/ui-internship-lwo2 pull request #3
Opened 2019-04-26 08:12 UTC by KamilWasilonek

2019-04-26 09:00 UTC, tkachukivan requested changes

2019-04-26 09:00 UTC, tkachukivan commented on tasks/21_check-letters/check-letters.js
> +    if (arr[0].toLowerCase().indexOf(letter) === -1) {
you can use `includes` method instead of `indexOf`

2019-04-26 09:00 UTC, tkachukivan commented on tasks/23_seek-destroy/seek-destroy.js
> +  return arr.filter((item) => args.indexOf(item) === -1 );
`includes` :)

2019-04-26 09:00 UTC, tkachukivan commented on tasks/24_index-to-insert/index-to-insert.js
> +  return arr.sort((a, b) => a-b)
spaces `a - b `

2019-04-26 09:00 UTC, tkachukivan commented on tasks/25_rot13-encoder/rot13-encoder.js
> +        if (letter.charCodeAt() >=65 && letter.charCodeAt() <= 77) {
you use multiply times `letter.charCodeAt()` better to make a variable for this and use this variable

2019-04-26 09:00 UTC, tkachukivan commented on tasks/27_basic-subclasses/basic-subclasses.js
> +    return [new Man('Adam', 'male'), new Woman('Eve', 'female')];
it is better to pass `male` or `female` from `Woman/Man` class, as in your implementation I can easily make from `male` `female` or even `animal`

2019-04-26 09:00 UTC, tkachukivan commented on tasks/29_remove-duplicates/remove-duplicates.js
> +    if (unique.indexOf(item) === -1 ) {
`includes`
or cheat a bit and use `Set` :D to remove duplicates

2019-04-26 09:00 UTC, tkachukivan commented on tasks/30_people-in-bus/people-in-bus.js
> +  arr.map((item) => (sum += item[0] - item[1]));
don't you think that it is a great place to use `reduce` method ?

2019-04-30 10:14 UTC, tkachukivan approved these changes

2019-05-13 11:08 UTC, mikhail-ev approved these changes

2019-05-13 11:08 UTC, TargetTaiga commented on tasks/22_remove-falsy-values/remove-falsy-values.js
> +  return arr.filter((item) => Boolean(item));
arr.filter(Boolean)

2019-05-13 11:53 UTC, merged