Tasks 71-80
KamilWasilonek/ui-internship-lwo2 pull request #8
Opened 2019-05-13 13:48 UTC by KamilWasilonek

2019-05-13 14:34 UTC, tsvetkovv requested changes
I think you should turn on the rule [eqeqeq](https://eslint.org/docs/rules/eqeqeq)

2019-05-13 14:34 UTC, Tsvetkovv commented on tasks/71_binary-encode/binary-encode.js
> +      .split('')
split for letters

2019-05-13 14:34 UTC, Tsvetkovv commented on tasks/71_binary-encode/binary-encode.js
> +            .split('')
and split letter for letter? item is letter already

2019-05-13 14:34 UTC, Tsvetkovv commented on tasks/72_carrying/carrying.js
> +  if (a && b) {
what if `a` or `b` would be 0?

2019-05-13 14:34 UTC, Tsvetkovv commented on tasks/72_carrying/carrying.js
> +    if (typeof a === 'number' && typeof b == 'number') {
`==` should be `===`

2019-05-13 14:34 UTC, Tsvetkovv commented on tasks/72_carrying/carrying.js
> +        if (typeof num !== 'number') {
please don't smear logic of checking arguments. Just check once on the top

2019-05-13 14:34 UTC, Tsvetkovv commented on tasks/72_carrying/carrying.js
> +  if (a || b) {
Why do you check first argument? It is possible to call `addTogether(undefined, 1)`?

2019-05-13 14:34 UTC, Tsvetkovv commented on tasks/73_check-for-palindromes/check-for-palindromes.js
> +  return str === reversed;
correct. Is it possible to check without array reverse?

2019-05-13 14:34 UTC, Tsvetkovv commented on tasks/74_dna-pairing/dna-pairing.js
> +  for (let i = 0; i < str.length; i++) {
it's simpler to use `map` function.

2019-05-13 14:34 UTC, Tsvetkovv commented on tasks/74_dna-pairing/dna-pairing.js
> +    let DNAPair = new Array(str[i]);
you have array composed of 2 items.
first item is always `str[i]`
second item you can get from object without loop

2019-05-13 14:34 UTC, Tsvetkovv commented on tasks/79_calculate_primoral_of_a_number/calculate_primoral_of_a_number.js
> +      result.push(i);
you could multiple by result at place

2019-05-13 14:34 UTC, Tsvetkovv commented on tasks/80_sum-of-prime-indexes/sum-of-prime-indexes.js
> +  let primeIndexes = [];
the same. Why array, not sum?

2019-05-14 08:20 UTC, tkachukivan approved these changes
Do changes which Viktor requested

2019-05-14 08:20 UTC, tkachukivan commented on tasks/71_binary-encode/binary-encode.js
> +              binary = '0'.repeat(padding) + binary;
String.prototype.leftPad?

2019-05-14 08:20 UTC, tkachukivan commented on tasks/75_complementary-dna/complementary-dna.js
> +    Object.keys(DNAPairs).forEach((key) => {
why do you need this loop here when you can just get object property?

2019-05-14 08:20 UTC, tkachukivan commented on tasks/76_deep-object-clone/deep-object-clone.js
> +    if (objToClone[key] != null && typeof objToClone[key] == 'object') {
===

2019-05-14 08:20 UTC, tkachukivan commented on tasks/77_expressions-matter/expressions-matter.js
> +  result.push(arr[0] * (arr[1] + arr[2]));
it would be fine here to use just variables

2019-05-14 08:20 UTC, tkachukivan commented on tasks/77_expressions-matter/expressions-matter.js
> +  arr = arr.sort((a, b) => a - b);
there is a point in tasks that you don`t have to change order of parameters, when you so you will find out that there is some broken tests :)

2019-05-14 10:03 UTC, tsvetkovv approved these changes

2019-05-14 10:03 UTC, tsvetkovv commented on tasks/74_dna-pairing/dna-pairing.js
> +  return [...str].reduce((result, item) => {
why not map?

2019-05-14 10:03 UTC, Tsvetkovv commented on tasks/79_calculate_primoral_of_a_number/calculate_primoral_of_a_number.js
> +function isPrime(num) {
I think you can write this function once at top directory and reuse the one in a few tasks to reduce code duplication.
Feel free do it or not

2019-05-28 11:18 UTC, merged